event:
    pattern:  /
    defaults: { _controller: "EventBundle:Event:index" }

event_show:
    pattern:  /{slug}/show
    defaults: { _controller: "EventBundle:Event:show" }

event_new:
    pattern:  /new
    defaults: { _controller: "EventBundle:Event:new" }

event_create:
    pattern:  /create.{_format}
    defaults: { _controller: "EventBundle:Event:create", _format: html }
    requirements: { _method: post }

event_edit:
    pattern:  /{id}/edit.{_format}
    defaults: { _controller: "EventBundle:Event:edit", _format:html }

event_update:
    pattern:  /{id}/update.{_format}
    defaults: { _controller: "EventBundle:Event:update", _format:html }
    requirements: { _method: post }

event_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    requirements: { _method: post }

event_attend:
    pattern:  /{id}/attend.{_format}
    defaults: { _controller: "EventBundle:Event:attend", _format: html }
    requirements:
        _format: html|json

event_unattend:
    pattern:  /{id}/unattend.{_format}
    defaults: { _controller: "EventBundle:Event:unattend", _format: html }
    requirements:
        _format: html|json